### ISSUE TITLE
In absence of pcrc32 and crc32

### ISSUE THREAD

**Issue by gr211** [aswaving/yenc#17]
Hi.

First, thanks for your code. Much appreciated.
Second, I'm reasonably new to Yenc, please forgive any errors on my part.

Problem statement
================

Say you have

```
=ybegin part=6 total=10 size=10012776 name=some_name.part21.vol331+32.par2
=ypart begin=5242881 end=6291456
<LOTS_OF_FUNKY_LOOKING_CHARACTERS>
=yend size=1048576 part=6
```

The code will throw an error saying

```
DecodeError(InvalidHeader { line: "=yend size=1048576 part=6\r\n", position: 25 })
```

because it would have liked to see

```
=yend size=1048576 part=6 pcrc32=bd441061 crc32=bd441061 #made up checksums
```

However, if that `=yend` line is actually missing altogether, then the code relies on byte counting using `size=10012776` .

But this assumes that all the bytes were accounted for. That is, not just `part=6` but every other part. Which of course are not there (yet).

One could (eventually) re-assemble all those parts, but it would nonetheless still be byte counting (short of checksum proof)

Alternative
=========

In lieu of 

```
if let Some(expected_size) = metadata.size {
   if expected_size != num_bytes {
      return Err(DecodeError::IncompleteData {
         expected_size,
         actual_size: num_bytes,
       });
     }
}
```

Wouldn't it be just equivalent to count "local" bytes rather, ie

```
if let Some(end) = metadata.end {
   if let Some(begin) = metadata.begin {
      let expected_size = end - begin + 1;
         if expected_size != num_bytes {
            return Err(DecodeError::IncompleteData {
               expected_size,
               actual_size: num_bytes,
            });
         }
      }
}
```
or something to that effect ?

**Comment by aswaving** [comment]
Hi, thanks for raising this issue. Yes, it's an improvement in case the `=yend` line is missing. Feel free to create a pull request. It would be nice if there are then also test cases for this.

**Comment by gr211** [comment]
Hi 

I created a [pull request](https://github.com/aswaving/yenc/pull/18/files). It does not run the GH action cause it needs your approval first.

I added tests that do pass on my machine. I did run into some CRLF issues with github auto.crlf. I think I pushed it right and it indeed does pass on ["my" GH CI"](https://github.com/grumlimited/yenc/actions/runs/12260583803/job/34205551815). So should it on yours hopefully.
